behaviors:
  MoveToGoal:
    trainer_type: ppo
    keep_checkpoints: 100
    checkpoint_interval: 1000000
    hyperparameters:
      batch_size: 2048
      buffer_size: 8192
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 10000
